### ISSUE TITLE
Update doc/teacher.md

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#1016]
We no longer need to manually deal with `Third-party access must not be restricted.` We should remove this from the documentation.

Review the remaining part of `doc/teacher.md` for other issues that needs to be updated.

@JosteinLindhom Please also take a look and comment if there are other issues that are no longer needed.

**Comment by JosteinLindhom** [comment]
The docs mentions this:

>  The teacher that created the course can promote users to teacher status and demote them back to the student role.

This is currently true for *all* teachers, not just the course creator. We should either update the text, or enforce that only course creators can promote users to the teacher role.
