### ISSUE TITLE
Use installation event to create course

### ISSUE THREAD

**Issue by JosteinLindhom** [quickfeed/quickfeed#1020]
When we install a GitHub application on an organization we receive an `Installation` event on our server. This event should contain sufficient information for creating a course.

The event does *not* contain sufficient information to fully configure a course (e.g. assigning a course name, slip days).

**Comment by meling** [comment]
Question:
- Does it make sense to record course information in the database before installing the QuickFeed GitHub application?
- If the QuickFeed application installation fails, perhaps we could also fail the course create database transaction? (to avoid half-registered courses in the database that would prevent a new attempt later on.)

**Comment by meling** [comment]
I think this has been resolved via #1029. I guess we forgot to update the link to this issue when we closed #1021. Do I have that right, @JosteinLindhom ?

**Comment by JosteinLindhom** [comment]
> I think this has been resolved via #1029. I guess we forgot to update the link to this issue when we closed #1021. Do I have that right, @JosteinLindhom ?

That is correct.
