### ISSUE TITLE
Use organization webhook events to accept member invites

### ISSUE THREAD

**Issue by JosteinLindhom** [quickfeed/quickfeed#1022]
The [member invited](https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=member_invited#organization) event could (possibly) be used to trigger logic to accept invites on behalf of users.

To recieve these events we must subscribe to `Organization` events in our GitHub app:

![image](https://github.com/quickfeed/quickfeed/assets/1346291/23960bff-ebed-44aa-8692-c60ba42303dd)

Currently QuickFeed trigger users to be invited to the organization when they are added to teams as part of group creation.

**Comment by meling** [comment]
Maybe the GitHub app manifest needs to be updated to select organization.
