### ISSUE TITLE
Allow teachers to run tests from their -labs repository

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#1047]
It looks like teachers can't create their own group and thus needs to create and join the course as a "simulated" student. This is inconvenient and unnecessary in most situations. We should allow teachers to run tests from a teacher's `-labs` repository also for group labs. 

This is important for teachers debugging their tests.

**Comment by JosteinLindhom** [comment]
Teachers *should* be able to create their own group. Teachers need to toggle the switch in the top navbar to view a course as student, then navigate to the `/course/<id>/group` page, or click the `Create group` button.

![image](https://github.com/quickfeed/quickfeed/assets/1346291/2dbb69e3-42b0-47ff-93ab-3a221232a21b)

**Comment by meling** [comment]
I've been thinking more about this one.

I'm leaning towards allowing single-member groups to push to non-group repositories (i.e., `-labs` repos), and have the tests executed, results recorded, and viewable in the frontend. The backend portion of this should be relatively easy to solve. Not sure how it would impact the frontend though; could you check @JosteinLindhom ?

However, we should define the rules more precisely, and think through how things should interact with #1053.

What should be the rules?

- If a student pushes to a `-labs` repo for a group lab, and is member of a group, notify somehow (see below).
- If a student (or group) pushes to a branch, should we run tests and record results? I think the simple answer is to ignore branches for both student repos and group repos. Only run tests for default branches.
- We currently don't use the PR review feature, but as mentioned in #1053, we should run tests and record results on a branch if there is an associated PR.

Some potential solution ideas:
- We could notify students by committing a file and commit message on their repo (and push to GitHub) to explain that they have pushed a change (related to a group lab) to their student repo, when the student is part of a group. (This could possibly trigger an email from GitHub as well...)
- We could notify students in the frontend.
- The concern with both solutions is that a student may drop out of a group, and thus continue to get notifications if the student switches to the student repo mid-semester after having been part of a group earlier.

One additional idea:
- We could allow students to add a `.quickfeed_ignore` file to their repo, which would disable test runs. Probably not.

Thoughts?

**Comment by JosteinLindhom** [comment]
#1123 makes submissions for group assignments made by users to their personal repositories viewable in the results view.
