### ISSUE TITLE
Switching between teacher and student mode needs improvement

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#1050]
When switching from teacher mode to student mode (and vice versa), the display should show useful information immediately instead of having to click the arrow. For example, when:

- teacher -> student: show the overview of course labs. If the student is enrolled in more than one course, we should show the course selection page.
- student -> teacher: show the results or course overview. If there are more than one course, we should show the course selection page.

Multiple courses: If student or teacher is active in more than one course, then we could assume that only the current year/semester's course is the active one. But if there are multiple courses in the same year/semester, we should show the course selection page when switching.

We should also update the toggle switch when switching; right now it isn't changing. The toggle switch could also be made a bit larger. Could we show the text `Teacher` and `Student` inside the toggle, or next to it, depending on the active mode?

**Comment by JosteinLindhom** [comment]
The toggle between teacher and student is linked to the currently selected course. Toggling between the two statuses only affects a single course.

The referenced commit above addresses your point about having to click the arrow in order to see useful information.

The toggle switch has been updated such that it always reflects the change when switching.

**Comment by meling** [comment]
Are there anything remaining in this issue to be addressed? If not, what remains to be fixed. And are they difficult to fix?

**Comment by JosteinLindhom** [comment]
> Are there anything remaining in this issue to be addressed? If not, what remains to be fixed. And are they difficult to fix?

What has not been implemented is:
- Showing `Teacher` / `Student` inside or next to the toggle switch
- Being taken to course selection if multiple courses for the current semester exist

The first one should be easy to fix.

For the second one some alternatives are:
- Take the user to the course selection page if multiple courses for the current semester exist
  - Need to add a way to toggle a course from the course selection page
- Make the toggle affect all current semester courses the user is teacher in (semi-global toggle)
  - Need to add some way to toggle for previous semester courses in this case
- Make the toggle affect *all* courses the user is teacher in (global toggle)

However I'm not sure how helpful toggling roles in courses unrelated to the currently selected course is.

**Comment by meling** [comment]
If it is possible to determine the currently active course, then toggling that course makes sense. If not, then 
- perhaps the course selection page should be shown?
- Or maybe it is easier to show an error/alert message to indicate that toggling student/teacher mode requires an actively selected course somehow?

**Comment by JosteinLindhom** [comment]
> If it is possible to determine the currently active course, then toggling that course makes sense. If not, then
> 
> * perhaps the course selection page should be shown?
> * Or maybe it is easier to show an error/alert message to indicate that toggling student/teacher mode requires an actively selected course somehow?

Navigating to a course makes it the currently active course.

Currently the toggle is only shown if:
- A course is active
- The user is a teacher in the active course

**Comment by meling** [comment]
Ok; then it seems this issue is already fixed to my satisfaction. If you agree, let's close it.
