### ISSUE TITLE
Log details view is cut off short; it could expand to the bottom of the result view portion

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#1065]
See picture. We could expand the log details view to the bottom of the page, aligning with the result view to the left.

![Screenshot 2024-03-21 at 15 27 23](https://github.com/quickfeed/quickfeed/assets/810999/9f4c3623-60bd-49ba-9c14-d3f5972abe53)

**Comment by JosteinLindhom** [comment]
This was fixed in #1059.

**Comment by meling** [comment]
Closing as already fixed.
