### ISSUE TITLE
Rebuild the submissions when the test cases of an assignment changes

### ISSUE THREAD

**Issue by vinaysetty** [quickfeed/quickfeed#257]
Item 4: I only now realize what this said, and it's a good idea.

We can probably be more targeted than "all submissions", since we can check which assignment was changed in the tests repo, and rerun only the last submissions for a specific assignment. Hence, this sounds like a worthwhile thing to implement.

I believe it should be relatively easy to implement; do you want to give it a go @vinaysetty ?
If so, maybe you want to start a separate issue to discuss design etc.

You can take a look at UpdateTestsFromRepo and elsewhere in the assignments package. The update is triggered from the web/hooks package, which contains a few functions that can probably be reused.

**Comment by vinaysetty** [comment]
I can give it a try, but may be with some help as I am not familiar with the codebase that much.

**Comment by meling** [comment]
Closing. This can be handled with a manual button press in the frontend to Rebuild All for a specific assignment.
