### ISSUE TITLE
Group view for teachers

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#260]
The current list of groups is not helpful for teachers to identify those that have been approved/not approved. We need a display mode for teachers that can show "real names" of students.

Ideas to ponder:
- We could have a toggle button at the top of the page that replaces the group with one line per student, copying the lab approvals from each group to its members
- Create a separate view to show all the labs of all students, including their group labs, and whether or not it has been approved.

In addition to one of the above solutions we should be able to export the students lab approvals as a csv file.

Further, we should require the student to use their full name (as listed on Canvas) in Autograder. We should add a description to this effect for the student signup phase. That is, saying that we will not accept a student to a course on AG without being listed on Canvas. We could have simple checks that both first name and last name is provided, and that it doesn't contain a number.

@0xf8f8ff Thoughts?

**Comment by 0xf8f8ff** [comment]
I like the idea of an additional view with both group and individual lab information, this way we can build it with csv-compatibility in mind. Besides, other course-specific options can be added there later, e.g. how many individual or group labs have to be approved to mark the student as passing, or an option to show/hide students who fail the course, and so on.

**Comment by meling** [comment]
Just adding to the discussion. We should made a new view that show all students, which labs they have approved and how much they contributed, e.g. some statistics regarding LoC and number of commits. We should have two modes of viewing the full list of students:

- Show students sorted across all students (e.g. sorted by first name or last name)
- Show students sorted by group affiliation (so that it is easy to detect free-riders).

**Comment by meling** [comment]
There is now a command line tool to extract approvals from quickfeed, saved as an Excel sheet suitable for the format required by fagpersonweb.

**Comment by JosteinLindhom** [comment]
> The current list of groups is not helpful for teachers to identify those that have been approved/not approved. We need a display mode for teachers that can show "real names" of students.
> 
> Ideas to ponder:
> 
> * We could have a toggle button at the top of the page that replaces the group with one line per student, copying the lab approvals from each group to its members
> * Create a separate view to show all the labs of all students, including their group labs, and whether or not it has been approved.

This part of the issue has been implemented.

**Comment by JosteinLindhom** [comment]
Actually, the last part is as well. I misread and thought you were referring to what is described in this issue: https://github.com/quickfeed/quickfeed/issues/261.

**Comment by JosteinLindhom** [comment]
> Just adding to the discussion. We should make a new view that show all students, which labs they have approved and how much they contributed, e.g. some statistics regarding LoC and number of commits. We should have two modes of viewing the full list of students:
> 
> * Show students sorted across all students (e.g. sorted by first name or last name)
> * Show students sorted by group affiliation (so that it is easy to detect free-riders).

This is related to https://github.com/quickfeed/quickfeed/issues/263

**Comment by meling** [comment]
Ok; seems like we could close this issue and move the "statistics regarding LoC and number of commits" portion to #263.

**Comment by meling** [comment]
Closing as (mostly) already resolved via already merged PRs. The remaining parts is covered by #263.
