### ISSUE TITLE
Remove GitHub repositories when rejecting a user.

### ISSUE THREAD

**Issue by 0xf8f8ff** [quickfeed/quickfeed#309]

**Comment by meling** [comment]
Do we need to create the user repos and group repos before approving a user/group? Currently also group repos are created before they are approved (e.g. when they are edited.)

**Comment by 0xf8f8ff** [comment]
Can't manage to recreate the issue:
- when a user is rejected from a course the corresponding student repository is deleted
- when a group is removed, the corresponding group repository is deleted
- if the group's or student's repository is not empty, an additional confirmation is requested
- no student repositories created before enrollment is approved
- no group repositories created before the group is approved
- when a group is edited and updated, it is automatically approved, then the repository for the group is created.

Is there anything I missed?

**Comment by meling** [comment]
Note to self: check if this is still a problem or not; close if fixed already. Also consider to add tests to check.
