### ISSUE TITLE
Consider how to treat teacher role

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#328]
Should the teachers be shown in the list of labs?
And should teachers receive their own repo?
Currently, we instead create student users using a separate GitHub account to imitate real student accounts.

Should the teachers have a separate signup page, where they can provide two accounts, and only create repo for the student account.
We could then give the name with suffix `(Student)` or something.
Would also be nice to be logged in as both somehow... so that the teacher can view the course as a student without logging in to the other GitHub user.

This is a discussion issue to collect ideas.

**Comment by meling** [comment]
Related to this, in the group member selection, teachers show up as possible partners. And students can actually select a teacher to be in group with. This should not be possible.

**Comment by meling** [comment]
My conclusion is that we don’t need to create separate student repos for teachers. This can be done manually if needed; usually only necessary for testing quickfeed access as students. However, we now have in the new frontend, the “show as student” view that removes this need.

We should show teachers in the list of labs, but there should be a toggle to remove teachers from the results view.

**Comment by JosteinLindhom** [comment]
Regarding your last point, the frontend now allows you to filter teachers from the Results/Reviews view.

However, the issue regarding teachers in group member selection is still present. #776 should fix this.

**Comment by meling** [comment]
I guess this is now fixed by #776. The only issue I'm not sure about now: Can I as a teacher create a group, e.g., together with another teacher? This would be nice to have for testing group assignments, without having to join a course as a "fake" student.
