### ISSUE TITLE
Limit group name length and possibly avoid space and comma

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#345]
Some take the group name to the extreme. Prevent creating group names that take up too much space in the teacher Result view and maybe we should avoid space and comma in group names.

**Comment by meling** [comment]
Keep it simple: disallow all special chars, including space. Only letters and numbers; not sure if we should allow æøå… 

Length limit: what looks okay in the teacher view? Maybe 20-25 max?

**Comment by JosteinLindhom** [comment]
The redesigned frontend enforces only alphanumerical group names, with a maximum length of 25 characters. However, this could still be bypassed with some console wizardry. We could also consider doing input validation on both the frontend and the backend to limit wizards ability to perform magic.
