### ISSUE TITLE
History of student scores

### ISSUE THREAD

**Issue by r0qs** [quickfeed/quickfeed#393]
Currently, it does not seems to be possible to inspect the history of the students' scores.
Would be nice to have such feature in the web frontend, since due to some bugs in the tests, the score of the student may change with resubmissions, and TAs should be able to confirm if the student indeed had a higher score in the past.

**Comment by meling** [comment]
Sounds reasonable. @0xf8f8ff can you comment on whether or not we already have the relevant data in database. If we do, this would be a matter of requesting it from the database and displaying it in the frontend.

**Comment by 0xf8f8ff** [comment]
At the moment we only record the last submission and its scores. We could of course record each submission as before, but, as we experienced, a student can make over a hundred pushes for a single assignment so it would just bloat a database for a feature that (if I understand correctly?) is only needed once in a while.

Alternatively, we could record the highest score achieved by the student for the given lab. A potential issue: an incorrect test that gives higher score than intended. To prevent this we could give teachers an option to reset higher scores for an assignment.

**Comment by meling** [comment]
I've thought some more about this, and I think the better solution is to require the student to fix their code to regain the required score after a bug in the tests has been fixed... This is explained in #539. That is, I think we should instead implement #539. Let me know if you have thoughts. If you agree, we can close this.
