### ISSUE TITLE
scm tool: add support for cleaning a github organization

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#47]
It would be nice to have a single command in the **scm** tool to

- remove all repositories 
- remove all teams
- remove all users
- remove all authorizations (not sure about this??)

The idea would be to clean out an organization to ready it for a new year.

@s111 Your input/opinion is requested.

**Comment by s111** [comment]
I'm not a big fan of the clean out and re-use an organization for each year approach, but maybe it's simpler for GitHub... I do however think we should add these methods to the SCM interface and it should then be a simple matter to expose them in the scm tool. It's atleast useful for our own testing purposes, and maybe we can have a cleanup option in the frontend too.

**Comment by meling** [comment]
Overlaps with #562 ; merge this into #562.

**Comment by meling** [comment]
Closing as already implemented.
