### ISSUE TITLE
Fix webhook secret handling

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#480]
We read from the `WEBHOOK_SECRET` environment variable but don't actually set it when starting the quickfeed server.

Perhaps the webhook secret should instead be generated and recorded in the database. There are two alternatives:
- generate when first initializing the quickfeed database (webhook secret per quickfeed instance)
- generate when creating a new course (webhook secret per course)

@JosteinLindhom Did you look into this before?? I seem to recall you mentioned something related to this before.
@0xf8f8ff Do you have any thoughts on this?

**Comment by 0xf8f8ff** [comment]
I like the per-course approach best, should be easy to implement as well by adding some `WHSecret` column to the `Course` table.

**Comment by meling** [comment]
> I like the per-course approach best, should be easy to implement as well by adding some `WHSecret` column to the `Course` table.

Yes. I agree.

**Comment by 0xf8f8ff** [comment]
One issue I see with course-level secrets: we validate hook event payload against a secret before getting access to the payload, but we have to get access to the payload first to know which course the event is coming from and fetch the secret from the database.
