### ISSUE TITLE
Creating new course with existing course-info

### ISSUE THREAD

**Issue by leandernikolaus** [quickfeed/quickfeed#504]
I created a new course, but did already have a course-info repo in the organization.

Autograded did not allow me to create the new course, so a renamed the course-info repo to `test`.

Now autograder let me create the course, but it did not create a new course-info repo. Instead, the `test` repo is linked as course-info.

**Comment by meling** [comment]
Not sure why this happened. Although it isn't recommended to have any repositories in the organization when creating the course. Maybe we should make the documentation text more clear on this. It is recommended that you have the "original" `course-info` repo in a separate org, e.g., `dat320/dat320` (org/repo), and then copy from that version of course-info into the year-specific repo, e.g., `dat320-2021/course-info`.

**Comment by meling** [comment]
See last [bullet here](https://github.com/autograde/quickfeed/blob/master/doc/teacher.md#a-course-organization-has-several-requirements). We may need to describe the suggested organization principle... We have additional tooling for managing this in `dat320` and @r0qs has created a GitHub template with some of these tools. But we should probably also document this stuff in the `teacher.md`... but I can't do everything myself.

**Comment by meling** [comment]
There are two things to be considered here. 
- Add tests to check that the course creation logic works with existing repositories (not sure if the current logic is to fail if any of the Quickfeed repositories already exits or to allow some to exist... I think it should fail.
- The logic should be robust against failures -- that is to clean up the database and partial repository creation. Roll back if there was a failure...

**Comment by JosteinLindhom** [comment]
Closed, working as intended.
