### ISSUE TITLE
Allow wildcard certificates in envoy config generation

### ISSUE THREAD

**Issue by r0qs** [quickfeed/quickfeed#508]
The `DOMAIN` configuration in the `.env` file is used to match the domains in the `virtual_hosts` section of the envoy config, but it is also used as part of the path to the certificates in the `tls_certificates` section.
This may cause some problems when using wildcard certificates since the configuration of the domain may include subdomains, but the path would use the main domain. 

Furthermore, in the current script, the certificate's path is hard-coded to `/etc/letsencrypt/live/$DOMAIN/...`, which is restricted to Let's Encrypt certificates and should be changed to a more general approach.

I believe that the tool should have its own configuration or sufficient parameters to allow such changes and ease production deployment.

**Comment by meling** [comment]
Agree.

**Comment by JosteinLindhom** [comment]
Certificates are now handled internally in QuickFeed, and no longer relies on Envoy.

**Comment by meling** [comment]
Closing as no longer relevant.
