### ISSUE TITLE
Remove unnecessary GitHub invitations

### ISSUE THREAD

**Issue by 0xf8f8ff** [quickfeed/quickfeed#540]
An invitation to the `info` repository is being sent to the enrolled students, but it is unnecessary because the repository is public and everyone in the course organization will already have read access to this repo.

**Comment by meling** [comment]
We should try to find a way to work around the requirement to accept so many invitations. One way could be to display a separate accept dialog in the frontend that uses the user's token to accept things... Not clear if this will work.
