### ISSUE TITLE
Individual approval for group labs

### ISSUE THREAD

**Issue by racin** [quickfeed/quickfeed#566]
I want to be able to approve a single member of a lab group, without approving the rest of the group.

This semester in DAT520 we will allow the student to work together as a group in the submission of the labs, but they have to meet individually with the TA to have their work approved.

**Comment by meling** [comment]
I can certainly see the usefulness of this feature. I've looked at the code and it was not designed for this. If you want to look into this, I suggest starting with the database... See `database/gorm_submission.go:CreateSubmission` and the `check():79` function, which detects and stops you from creating a submission with both user and group. 

However, to support something like this, one way would need to duplicate the submission object, one for each member of a group. The submission object encodes a fair bit of stuff, including build logs etc (see below), so maybe not a good idea.

Another idea could be to change the status field a map indexed with the `userID` as the key and the `Status` as the value. But this would be touching a fair bit of code all over, and would require careful thinking about the logic. I didn't check all uses of Status, but my intuition is that this wouldn't be a trivial change.

```proto
message Submission {
    enum Status {
        NONE = 0;
        APPROVED = 1;
        REJECTED = 2;
        REVISION = 3;
    }
    uint64 ID = 1;
    uint64 AssignmentID = 2; // foreign key
    uint64 userID = 3;
    uint64 groupID = 4;
    uint32 score = 5;
    string commitHash = 6;
    bool released = 7;       // true => feedback is visible to the student or group members
    Status status = 8;
    string approvedDate = 9;
    repeated Review reviews = 10;     // reviews produced for this submission
    score.BuildInfo BuildInfo = 11;   // build info for tests
    repeated score.Score Scores = 12; // list of scores for different tests
}
```

@0xf8f8ff @JosteinLindhom Do you have any thoughts on this?
