### ISSUE TITLE
Discussion: Is course creator access token necessary for QuickFeed's access to course repos?

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#580]
Recently, we ran into a problem with the access token of course creators expiring; new tokens were issued and recorded in the database, but weren't updated in the access token cache for the `Course` type. This cache was added to simplify access to the token directly from the `Course` type. Note that the token is also cached in the `echo.Context` in the [`auth.updateScm()`](https://github.com/quickfeed/quickfeed/blob/master/web/auth/auth.go#L442).

My question is if this is an appropriate design choice for giving QuickFeed access to the different courses's repositories? That is, is there another way to do this?

It would seem that the access token might be invalidated if the course creator logs out of GitHub. (I have not tested this.)

**Comment by 0xf8f8ff** [comment]
I feel like it's related to the third party authentication process for apps at the organization level I mentioned recently, so yeah I'm looking into this as well.

**Comment by meling** [comment]
Hmm. I never really paid any attention to the GitHub Apps thing... I just skimmed the top of this [doc page](https://docs.github.com/en/developers/apps/getting-started-with-apps/about-apps#about-github-apps), and this looks like what we actually want to use.
