### ISSUE TITLE
Approved status of a submission resetting on a new push to the -labs repo

### ISSUE THREAD

**Issue by 0xf8f8ff** [quickfeed/quickfeed#582]
Approved status of a submissions for an assignment with manual review resets back to `Not approved` after a new push to the student's repo.

**Comment by 0xf8f8ff** [comment]
Could this please be solved one way or another? This bug currently affects around 300 users, students waste their time to get approved before deadline and lose the approved status next day, TAs have to check and reapprove submissions multiple times and keep lists on paper. It's not just a minor inconvenience, really.

**Comment by meling** [comment]
Please see the #589. I'm awaiting your input on my revised version. As soon as we agree we can deploy.

**Comment by meling** [comment]
Has this been solved?

**Comment by 0xf8f8ff** [comment]
> Has this been solved?

Yes.

**Comment by meling** [comment]
Closing via #599 and #597 and #583 and #588
