### ISSUE TITLE
Running Go-tests on Windows

### ISSUE THREAD

**Issue by Synnems** [quickfeed/quickfeed#585]
When running Go-tests on windows an error occurs. The process cannot access the file because it is being used by another process. 

`== RUN   TestSubmissionsAccess
    test_helper.go:41: remove C:\Users\AppData\Local\Temp\TestSubmissionsAccess3275008097\001\test.db873990541: The process cannot access the file because it is being used by another process.       
    testing.go:967: TempDir RemoveAll cleanup: remove C:\Users\AppData\Local\Temp\TestSubmissionsAccess3275008097\001\test.db873990541: The process cannot access the file because it is being used by another process.
--- FAIL: TestSubmissionsAccess (0.24s)`

**Comment by meling** [comment]
Closed by #586
