### ISSUE TITLE
Grade of a first graded criterion not recorded in the database when a new review created

### ISSUE THREAD

**Issue by 0xf8f8ff** [quickfeed/quickfeed#591]
A new manual review is usually created when a TA marks (grades) one of the review criteria as pass/fail. However, currently a review is created correctly (with a correct score), but the graded criterion saves without any grade in the database. 

The bug is only present when a new review is created, on updates everything works as it should.

**Comment by JosteinLindhom** [comment]
The source of this change in behaviour is in this commit: https://github.com/quickfeed/quickfeed/commit/9a44e4ae9c666205f88f65cab74f767bbfd69933. 

In the redesigned frontend a reviewer has to click a button to start reviewing, upon which a new review is created and displayed. The backend returns a new review pre-populated with benchmarks an criteria

```ts
        const review = new Review
        // Set the current user as the reviewer
        review.setReviewerid(state.self.getId())
        review.setSubmissionid(submission.getId())
        const response = await effects.grpcMan.createReview(review, state.activeCourse)
        // response.data contains the newly created review, pre-populated with benchmarks and criteria from the database
```
This made review creation a lot easier in the redesigned frontend, but has the side effect you describe.

**Comment by JosteinLindhom** [comment]
The change requires only that submission ID and reviewer ID be set in the passed in review when creating a review. 
Benchmarks and criteria passed, if any, will be replaced by those in the database. 
Therefore, when a new review is created, and a graded criterion is passed along, it will not be registered. As a consequence, the first grading in the old frontend will not "count", but subsequent gradings will.

**Comment by 0xf8f8ff** [comment]
Yup, got it. So should I direct TAs that use this feature right now to use the new UI? I guess they still have no idea about its existence.

**Comment by meling** [comment]
Another alternative would be to fix it in the old forntend as well? Would that be difficult? If so, I don’t mind them using the new UI, but I’m sure it is quite ready yet…

**Comment by meling** [comment]
Has this been solved in the old frontend?

**Comment by 0xf8f8ff** [comment]
> Has this been solved in the old frontend?

No. But we've learned to live with it.

**Comment by JosteinLindhom** [comment]
This is no longer an issue as the old frontend has been removed.
