### ISSUE TITLE
Teacher view progress bar is not displayed correctly

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#606]
The new frontend does not display the progress bar correctly. We should only show the `xx % to go` and not the `xx/xx` part as well.

![Screen Shot 2022-02-08 at 19 59 51](https://user-images.githubusercontent.com/810999/153056949-15cbf6fe-dd4b-445e-b00a-9b5f456e2bb2.png)

**Comment by JosteinLindhom** [comment]
This should be fixed in 446c8a35b94660a730af1d9f7449a8d81bb4bb3c. Try  a hard refresh and let me know if its still an issue.

**Comment by meling** [comment]
Yeah; hard-reset did the trick. Closing as already fixed.
