### ISSUE TITLE
Student repository links still have "master" as default branch

### ISSUE THREAD

**Issue by 0xf8f8ff** [quickfeed/quickfeed#608]
Repository links have the following format: `course_org/student-labs/tree/master/assignment_name`, but the default GitHub repo branch is now `main`. Generally, it still works because GH redirects to the default `main` branch when there is no `master` branch.

However, some students follow outdated instructions and manage to also create a `master` branch in their `-labs` repos. After that the link:
- returns 404 if there is no folder for the corresponding assignment on the `master` branch
- opens the wrong assignment folder which can result in grading errors

**Comment by meling** [comment]
The only place where the string `tree/master` appears is in this function (public/src/componentHelper.tsx):

```typescript
export function userSubmissionLink(login: string, assignmentName: string, courseURL: string, style?: string): JSX.Element {
    return <a className={style} href={labRepoLink(courseURL, login) + "/tree/master/" + assignmentName} target="_blank">Open repository</a>
}
```

Should we update this function to use `tree/main`? Would it help?

Where are these outdated instructions? I assume such instructions are in the dat310 course? Maybe you could update those instructions. I'll check dat320 and dat520.

**Comment by 0xf8f8ff** [comment]
> Should we update this function to use `tree/main`? Would it help?

Yes, absolutely.


> Where are these outdated instructions? I assume such instructions are in the dat310 course? Maybe you could update those instructions. I'll check dat320 and dat520.

From what I understand, many of students have no experience with git, so they try to google solutions, end up copying commands from old articles or stackoverflow posts and end up with a non-default master  branch.

**Comment by meling** [comment]
> > Should we update this function to use `tree/main`? Would it help?
> 
> Yes, absolutely.

Okay. I'll update and push directly to master; shouldn't be necessary to do PR and reviews for this.
 
> > Where are these outdated instructions? I assume such instructions are in the dat310 course? Maybe you could update those instructions. I'll check dat320 and dat520.
> 
> From what I understand, many of students have no experience with git, so they try to google solutions, end up copying commands from old articles or stackoverflow posts and end up with a non-default master branch.

Hmm. Is there something more we can do to avoid these problems?

**Comment by 0xf8f8ff** [comment]
> Hmm. Is there something more we can do to avoid these problems?

I think this won't be a problem any longer when the link points to the `main` branch.

**Comment by meling** [comment]
Fixed via direct push to master. Will restart server in a few minutes. Let's reopen the issue if this doesn't solve the problem.
