### ISSUE TITLE
uis: Backup the database on Quickfeed daily

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#611]
Use the crontab.daily feature to backup the database in case of bugs that mess up the database...

**Comment by JosteinLindhom** [comment]
Daily backup at 03:00 has been added on the server. Refer to the `backup.sh` file in `/quickfeed` and use the command `crontab -l` to view the scheduling.

**Comment by meling** [comment]
Excellent. Looks good to me. Could you add the script to the `doc/scripts` folder and just push to master; no need for a PR.
