### ISSUE TITLE
[Manual reviews] Some existing submissions not showing in the Review tab, then reappearing later on

### ISSUE THREAD

**Issue by 0xf8f8ff** [quickfeed/quickfeed#623]
There were multiple occurrences since last Friday when a student lab was showing "No submission" in the `Review` tab while there was a submission in the `-labs` repo. However, it shows all submission properly now even though there weren't any new pushes to the repositories (so it looks like the submissions have been recorded properly in the database on the initial push, just somehow not displayed in the Review tab). 

Moreover, it looks like one TA could see a submission for several students, but it was showing "No submissions" for the same students and assignment for another TA.

**Comment by meling** [comment]
Is this referring to the new frontend or the legacy one?

**Comment by 0xf8f8ff** [comment]
> Is this referring to the new frontend or the legacy one?

Confirmed in the legacy UI, not sure about the new one, will update in case of any new information.

**Comment by meling** [comment]
Closing as hopefully solved with the new frontend.
