### ISSUE TITLE
Harmonize SubmissionRequest and SubmissionsForCourseRequest

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#625]
I seems too difficult to harmonize these two RPCs because of the return types:
```proto
    rpc GetSubmissions(SubmissionRequest) returns (Submissions) {}
    rpc GetSubmissionsByCourse(SubmissionsForCourseRequest) returns (CourseSubmissions) {}
```
However, we can use the same request type for both RPC methods:
```proto 
message SubmissionRequest {
    uint64 courseID = 1;
    enum SubmissionType {
        ALL   = 0;  // fetch all submissions
        USER  = 1;  // fetch all user submissions
        GROUP = 2;  // fetch all group submissions
    }
    oneof fetchMode {
        uint64 userID       = 2;  // fetch single user's submissions
        uint64 groupID      = 3;  // fetch single group's submissions
        uint64 submissionID = 4;  // fetch single specific submission
        SubmissionType type = 5;  // fetch all submissions of given type
    }
    bool withBuildInfo = 6;
}
```
The `withBuildInfo` may only be needed for the **fetch all submissions** mode. Consider whether or not to respect `withBuildInfo` for the single user or group modes.

**Comment by meling** [comment]
This is related to #560.

**Comment by meling** [comment]
Currently the frontend seems to always ask for build info:
```typescript
const result = await effects.grpcMan.getSubmissionsByCourse(courseID, SubmissionsForCourseRequest.Type.ALL, true)
const groups = await effects.grpcMan.getSubmissionsByCourse(courseID, SubmissionsForCourseRequest.Type.GROUP, true)
```
However, I think it might make sense to drop this argument and don't include the build info in when fetching all submissions, but instead fetch it on-demand when viewing a specific "submission". What do you think @JosteinLindhom ??

**Comment by JosteinLindhom** [comment]
We could definitely do that. This will require a new method to retrieve the `BuildInfo` (or full `Submission`) for a given submission.
