### ISSUE TITLE
When accepting student to course the member list does not update with secondary problem

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#631]
When accepting a student to a course the member list does not update. Even after several minutes while composing this issue.

- Note that, I'm in the USA, so it could be due to a timeout that normally doesn't trigger.
- Another root cause could of course be packets being dropped on either side of the connection (I'm on a hotel WiFi, but we should be resilient to such problems...)
- Reloading fixes the problem.

However without reloading, if clicking again on accept, you will get a prompt asking if you are sure you I want to promote the student to teacher. This should not be the intended behavior.

The same problem also appears when promoting student to teacher. The member list does not update. In fact, when clicking again on `promote` actually demotes the teacher back to student (because the list wasn't reloaded).

**Comment by JosteinLindhom** [comment]
This should be fixed in #646.
