### ISSUE TITLE
Decide if db.GetTasks is needed

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#636]
We currently have a method:
```go
// GetTasks gets tasks based on query
func (db *GormDB) GetTasks(query *pb.Task) ([]*pb.Task, error) {
	var tasks []*pb.Task
	err := db.conn.Find(&tasks, query).Error
	if err != nil {
		return nil, err
	}
	if len(tasks) == 0 {
		return tasks, gorm.ErrRecordNotFound
	}
	return tasks, err
}
```
This is currently used only in tests; consider whether or not to keep this.

**Comment by oleespe** [comment]
When handeling late enrolling groups this method will become necessary, as we need it to get all the tasks of a course, and create issues based on them.
