### ISSUE TITLE
Convention: Decide on a convention for marking ID and foreign key ID fields

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#641]
The proto files define messages with `ID` fields required by the database. These are then sometimes used as foreign keys in other message types. We also have other `ID` fields, such as GitHub's `RepositoryID` which can be confused with the database internal ID for the `Repository` message type, when used as a foreign key.

Some ideas for a convention to distinguish these ID fields:
- Foreign keys for the database could be prefixed with `fk` or `db`.
- Remote/external IDs related to GitHub could be prefixed with `scm`.

Examples:
- `dbRepositoryID`
- `scmRepositoryID`

It looks like there is significantly more use of database foreign key IDs than external IDs. Thus, it might be reasonable to adopt the convention that all fields that end with `<MessageType>ID` represents a database foreign key, whereas requiring that all other fields that represents an external ID of some sort be prefixed with e.g., `scm<Name>ID`.

**Comment by JosteinLindhom** [comment]
We use `remoteID` in `RemoteIdentity`, which corresponds to the user's GitHub ID. If we go for the `scm<Name>ID` variant, we should rename this field using the convention we decide to be consistent.

**Comment by meling** [comment]
Closing as superseded by #945
