### ISSUE TITLE
Update the Pull request support to use the new GitHub web app approach

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#649]
Look for the string: `TODO(espeland): Update this for GitHub web app.`

These instances should be updated for the new GitHub web app implemented by @0xf8f8ff. If my recall is correct, the current approach creates PR comments as the course creator (typically the teacher). We should avoid this and let the actual TA or student's named be used on comments.

@oleespe Please add your insights regarding what is needed for updating to use the web app approach.

**Comment by oleespe** [comment]
In my project I use the SCM API to, amongst other things, create GitHub issues and issue comments.
Given that QF is not a GitHub web app (at time of writing), every API request with GitHub has to be done using tokens. 
This means that these issues and issue comments are always created as the user owning said token, which in the current implementation is always the course creator.

Having researched GitHub web apps during my project, I came to the understanding that if QF is implemented as one, it will be able to authenticate on its own authority. Meaning that we can create issues and issue comments as QF, and not some user.

This needs to happen in the functions `handleTasks()` and `handlePullRequestPush`.
The relevant scm client used by these two functions need to be altered to do as described, asuming that things work as I imagined.

**Comment by meling** [comment]
This should now be implemented. However, we need to add tests for this.

**Comment by JosteinLindhom** [comment]
Remove TODOs.

**Comment by meling** [comment]
Creating issues (for testing) is mainly done in `assignments.TestSynchronizeTasksWithIssues`. We currently don't have tests for creating PRs, I think.

To test this, we need to set up a GitHub app; currently, our tests use PAT's, which will create issues and PRs under the name of the PAT's owner. We also have `scm.TestSCMManager` that requires a GitHub app. We should consider adding a new environment variable to enable testing with a GitHub app. Still, it is unclear if we can run a GitHub app for testing without a running server via ngrok or similar.
