### ISSUE TITLE
Git checkout in script files

### ISSUE THREAD

**Issue by oleespe** [quickfeed/quickfeed#650]
As part of my project of implementing QF support for issues and pull requests, QF needed to have the capacity of running tests on non-default branches. To support this, the relevant branch name is passed as a variable to the script files that are run when testing student code.

For this this to actually work, the following lines of code must be added to these script files.
```
if [ {{ .BranchName }} != "main" ]; then
    git checkout {{ .BranchName }}
fi
```

**Comment by meling** [comment]
I have some code in the works that will clone the relevant git repos from within Go code. I think it should be straight forward to implement this checkout functionality as well. Leaving this open until this code is ready to be merged.

**Comment by meling** [comment]
PR #666 implements a git clone of `tests` and `student-labs` repos, including support for checking out a named branch.
