### ISSUE TITLE
Conform to a single task name format

### ISSUE THREAD

**Issue by oleespe** [quickfeed/quickfeed#651]
When tasks are created they are given a name, which in turn is used to map tasks existing in the database with tasks parsed from markdown files in the `tests` repository. This name is a combination of the name of the relevant markdown file and assignment folder.
For example, the markdown file `task-hello_world.md` in assignment folder `lab1` would produce the task name `lab1/hello_world`.

The task data structure also has a method `LocalName()` which returns only `hello_world`. This name is used in the score package when teachers add tests with task names, e.g., with `scores.AddWithTaskName(TestHelloWorld, "hello_world", max, weight)`.
The "local" task name is also used in other parts of the code.

Originally, including the assignment name as part of the entire task name was necessary to succesfully synchronize tasks.
In the current implementation however, this should no longer be needed. It would therefore be less confusing if we only confer to a single task name format, namely the local one.

**Comment by oleespe** [comment]
If this is implemented, any mention of different types of task names in code and documentation should be removed.

**Comment by meling** [comment]
I agree that the current practice with `lab1/hello_world` is confusing, especially when trying to understand the code. @oleespe Do you have any sense of how much effort would be required to switch to the more desirable approach?

I've actually renamed `LocalName()` to `TaskName()`, and was thinking about rename the `Task.Name` field to `FullName` to make things more clear. However, I now see that this will be unnecessary.

Does this mean that we cannot have `lab1/hello_world` and `lab2/hello_world`?

**Comment by oleespe** [comment]
We should still be able to have both `lab1/hello_world` and `lab2/hello_world` because given that `SynchronizeAssignmentTasks` synchronizes on a per assignment order basis. 

Swapping to the desired naming convention should require almost no work. I still have to test whether task actually correctly synchronize, but I do not see why not.

I can implement this.
