### ISSUE TITLE
Remove old frontend from codebase

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#657]
Tasks for removing the old frontend:
- [x] Delete `public` folder
- [x] Move new frontend from `dev` to new folder (to be decided: see below)
- [x] Update the `Makefile` to remove targets and other references to `public` (including `make ui`)
- [x] Update relevant documentation files, e.g., in `doc`
- [x] Paths in `main.go` that references location for storing static assets
- [x] Update location pointers in javascript code
- [x] Update .gitignore

@JosteinLindhom 
1. Should the location of current `dev` be moved to `public`?
2. Is there anything more we need to do?

**Comment by JosteinLindhom** [comment]
In #661 i added two endpoints for static files:
- static, which points to the `dist` folder.
- assets, which points to an `asset` folder containing stylesheets, images, etc.

I also renamed `dev` -> `public` there, but an alternative could be to only keep files that will be served to clients in this folder, and the actual source in a separate folder.

**Comment by JosteinLindhom** [comment]
Come to think of it, perhaps the folder generated by `make webpack-dev-server` should be added.
However, I have removed the need for this generated folder in my branch including webpack improvements.

**Comment by meling** [comment]
Weird. Why wasn't this issue closed when #661 was merged?
