### ISSUE TITLE
tm.GetClaims used in multiple interceptors

### ISSUE THREAD

**Issue by JosteinLindhom** [quickfeed/quickfeed#739]
Currently `GetClaims` is used in three separate interceptors. `GetClaims` decodes the JWT included in an incoming request.
Rather than decoding JWT and retrieving claims in three separate interceptors, we should consider decoding it only once and passing it down the interceptor chain.

**Comment by meling** [comment]
Maybe we could do something like this:
```go
func (c *Claims) Context(ctx context.Context) context.Context {
	return context.WithValue(ctx, ContextKeyClaims, c)
}

func ClaimsFromContext(ctx context.Context) *Claims {
	return ctx.Value(ContextKeyClaims).(*Claims)
}
```
