### ISSUE TITLE
Student code that doesn't compile results in missing tests in the results view

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#750]
Currently, if a student submits code that doesn't compile, the Tests and corresponding scores may not show up in the results view.

One idea to fix this is to build the tests with a custom version with the list of tests; they could be in the tests repo, protected by a special build tag. These tests should ideally give 0 score on all tests, as previously supported with the init stuff.

There isn't actually something to do in the kit/score package, but we could add tests of the functionality there, I think. That is, the functionality must be supported for each lab/course.

Not sure if the same problem exists for other courses that use python.

PS: A build failure can easily be caused by adding a build tag (not activated by the run.sh script) to student submitted code.

**Comment by JosteinLindhom** [comment]
Failure can be caused by referring to undefined variables.

```go
func scramble(text string, seed int64) string {
	rand.Seed(seed)
	tokens := tokenize(text)
	for i, token := range tokens {
		s // undefined
	}
	return ""
}
```
