### ISSUE TITLE
Build date or submission date

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#755]
We currently only update the "build date" when a student push to their repository. However, it would be nice to distinguish between the actual build date, e.g., for rebuild purposes, and the submission date when the student last updated their code in their repo. This would allow us to rebuild if a test were updated and see that the date actually change in response. As is, the date remains the same for rebuilds.

Conclusion: we need two different date fields in the results view...

Should be done in or on top of PR #704, or after it has been merged.

**Comment by JosteinLindhom** [comment]
The logic where this happens:

```go
// record_results.go
func (r RunData) newTestRunSubmission(previous *qf.Submission, results *score.Results) *qf.Submission {
	if r.Rebuild && previous != nil && previous.BuildInfo != nil {
		// Keep previous submission's delivery date if this is a rebuild.
		results.BuildInfo.BuildDate = previous.BuildInfo.BuildDate
	}
        ...
}
```

Perhaps an additional field in `BuildInfo`, ex. `RebuildDate`, could be added and set here.

**Comment by JosteinLindhom** [comment]
Also, in cases where the previous submission is approved and has `ApprovedDate` set, we should keep approved date in the new submission created in `newTestRunSubmission`.

Currently `ApprovedDate` is set when a submission is updated with status set to `Approved`. However if a student pushes changes, or a submission is rebuilt, the approved date does not carry over to the newly generated submission.
