### ISSUE TITLE
Support for third party apps

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#790]
With the revised security model, we no longer support `approvelist`, `helpbot`, the Swift UI client, and future applications that might want to invoke quickfeed RPC methods. PR #703 should fix this issue, when it is ready.

- [x] We should also remember to fix this test `web/grpc_auth_test.go:TestGrpcAuth`
- [x] Clean up the `const`s no longer needed
- [x] Rename the test to `TestAppAccess`
- [x] Rename the file to `app_access_test.go`

**Comment by JosteinLindhom** [comment]
This might be possible to implement through the GitHub [device flow](https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#device-flow). #703 is put on ice for the time being.
