### ISSUE TITLE
Manifest does not request write access for webhooks

### ISSUE THREAD

**Issue by JosteinLindhom** [quickfeed/quickfeed#815]
Apps created with the manifest flow currently do have permission to add webhooks. We need to specify an additional parameter in the request body we send to GitHub. `"organization_hooks": "write"` might do the trick.

**Comment by meling** [comment]
The current solution in #820 needs to be updated to subscribe to push events and possibly other events of interest.
See [this](https://docs.github.com/en/developers/apps/building-github-apps/creating-a-github-app-from-a-manifest) documentation.
