### ISSUE TITLE
`GetRepositories` is used mostly (except in tests) to check if an organization for a new course already has course repositories and probably should be returning a Boolean

### ISSUE THREAD

**Issue by 0xf8f8ff** [quickfeed/quickfeed#901]

**Comment by 0xf8f8ff** [comment]
It looks like this method is better left as it is for now. It is used by the `TestSynchronizeTasksWithIssues` test which tests interactions with GitHub API. Not sure if inventing workarounds for such tests is worth it for the minor gain of changing the return value type of `GetRepositories`.

**Comment by meling** [comment]
Leaving as is.
