### ISSUE TITLE
UpdateSubmissions has unused courseID argument

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#924]
```go
func (db *GormDB) UpdateSubmissions(courseID uint64, query *qf.Submission) error {
```
The method does not use the `courseID` argument in the update query. Similarly, the 
```go
func (s *QuickFeedService) updateSubmissions(request *qf.UpdateSubmissionsRequest) error {
```
and the `qf.UpdateSubmissionsRequest` probably does not need `courseID`, since `AssignmentID` should be unique.

Double check why this field is there.

**Comment by 0xf8f8ff** [comment]
`qf.UpdateSubmissionsRequest` got `courseID` to enable access control check without extra database lookups.
