### ISSUE TITLE
Chore: Update disabled tests

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#946]
There are still a few tests that are disabled with `t.Skip` that must be updated:

- [x] `web/courses_test.go: TestEnrollmentProcess`
- [x] `web/groups_test.go: TestDeleteGroup`
- [x] `web/users_test.go: TestUpdateUserFailures`
- [x] `database/gormdb_enrollment.go: UpdateEnrollment()`: See TODO(vera): Omitting ID ... 

Uncertain if these are helpful or can be mocked:

- [ ] `TestSCMManager`
- [x] `TestInitSCMs`

**Comment by 0xf8f8ff** [comment]
What should we do about `TestSCMManager`? I see no point in mocking it since it is designed to ensure that a new SCMManager is properly created given all the necessary env variables.  Is it not needed? If not, we should just remove it I guess.
