### ISSUE TITLE
Chore: Cherry pick changes from #704

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#949]
There are various changes in #704 that we may or may not want to bring forward before closing it.

- [x] `Database` interface changes (including logic updates):
  - [x] `GetAssignmentsByCourse(uint64) ([]*qf.Assignment, error)`
  - [x] `GetAssignmentsWithSubmissions(*qf.SubmissionsForCourseRequest) ([]*qf.Assignment, error)`
- [x] File `database/gormdb_assignment.go` has many changes
- [x] #951
- [x] `TestGormDBSubmissionWithBuildDate` in `database/gormdb_submission_test.go` is not in new PR. Not needed?
- [x] The new `time.Time`-based `TimestampSerializer` does not have a test see `database/timestamp_serializer_test.go`. Should we add one?
- [x] Does it make sense to add the trivial test in `public/src/**tests**/Timestamp.test.ts`
- [x] Should we keep `qf/submission_request.go` and `qf/submission_request_test.go`

The database changes should not be added to #947 since they are not related to the timestamp issue.

**Comment by 0xf8f8ff** [comment]
Added `TestGormDBSubmissionWithBuildDate` to #947.

**Comment by meling** [comment]
Closing since all relevant changes has been merged.
