### ISSUE TITLE
`GetOrCreateSCM` should log or return any errors that occur.

### ISSUE THREAD

**Issue by JosteinLindhom** [quickfeed/quickfeed#955]
`GetOrCreateSCM` returns `ErrMissingInstallation` regardless of what the error returned by `newSCMAppClient` is.

```go
ErrMissingInstallation = errors.New("github application is not installed on the course organization")
```

```go
// GetOrCreateSCM
    client, err := newSCMAppClient(ctx, logger, s.Config, organization)
    if err != nil {
        return nil, ErrMissingInstallation
    }
```

`newSCMAppClient` has a wide range of different errors it can return, but currently they are not used other than to check *if* there was an error.

In one case the error `github application is not installed on the course organization` was returned even though the app was installed on the organization. Some debugging revealed that the returned error from `newSCMAppClient` nothing to do with neither the application nor the organization:

```go
failed: not_found: error unmarshalling installation response: {"message":"'Expiration time' claim ('exp') is too far in the future","documentation_url":"https://docs.github.com/rest"}: json: cannot unmarshal object into Go value of type []*github.Installation
```

The error suggests that the machine sending the request to GitHub is affected by clock drift.

We should either:
1. Use the returned error.
2. Log the error, but still return a generic error to the user.

**Comment by meling** [comment]
Agree. We should return the error. We already log the error at all call-sites, and return a different `connect.Error` onwards to the gRPC client. Note that the `GetOrCreateSCM` is also called via the `getSCM` helper, which should show the call-sites where logging happens.

The error message from `GetOrCreateSCM` could be something like:
```go
fmt.Errorf("failed to create github application for %s: %w", organization, err)
```
